version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: techblog
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - ./techblog.sql:/docker-entrypoint-initdb.d/techblog.sql  # Add this line to load SQL on startup
    networks:
      - app_network

  innotechcommunity_web:
    image: tomcat:9-jdk21
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: techblog
      DB_USER: your_username
      DB_PASSWORD: your_password
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
